### ISSUE TITLE
Should unbind scroll and clicks events

### ISSUE THREAD

**Issue by itbabu** [cfenollosa/eu-cookie-law#3]
Hi @cfenollosa

```denyConsent()``` should unbind scroll and clicks events when a user deactivates the cookies.

You can test it in your blog: click "deactivate cookies", click a link to an other page... and the google analytics code is downloaded.

These 2 lines inside ```denyConsent()``` should fix this issue.
```
$(window).unbind("scroll");
$("a:not(.noconsent)").unbind("click");
```
Cheers

Marco

**Comment by cfenollosa** [comment]
Thanks Marco! I uploaded a fix
